/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class bracelet extends javax.swing.JFrame {
    int SILVER,GOLD,BLACK,ROSE,harga,bayar,kembali;
    /**
     * Creates new form bracelet
     */
    public bracelet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb_1 = new javax.swing.JRadioButton();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        rb_4 = new javax.swing.JRadioButton();
        bt_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_data1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_data3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbo_pembayaran = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tf_bayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_kembali = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        lbl_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        about = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(674, 406));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SMILE FOR YOU BRACELET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 280, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("VARIANT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        rb_1.setText("SILVER");
        rb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));

        rb_2.setText("GOLD");
        rb_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 30));

        rb_3.setText("BLACK");
        rb_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 30));

        rb_4.setText("ROSE GOLD");
        rb_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_4ActionPerformed(evt);
            }
        });
        jPanel1.add(rb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 30));

        bt_back.setBackground(new java.awt.Color(153, 153, 255));
        bt_back.setText("BACK TO HOME");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        jPanel1.add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("PRICE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(tf_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, 20));

        tf_data1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 140, 30));

        jLabel6.setText("No. Telpon");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 60, 20));

        tf_data3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 140, 30));

        jLabel7.setText("Pembayaran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        cbo_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cash", "Kurir" }));
        cbo_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_pembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 100, -1));

        jLabel10.setText("Bayar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 40, 20));
        jPanel1.add(tf_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 100, -1));

        jLabel9.setText("Kembalian");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 60, 20));

        tf_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(tf_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 100, -1));

        btn_bayar.setBackground(java.awt.Color.pink);
        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 180, -1));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/waall (2).jpg"))); // NOI18N
        jPanel1.add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/icons8-information-20.png"))); // NOI18N
        about.setText("About");
        about.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMousePressed(evt);
            }
        });
        jMenuBar1.add(about);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        exit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                exitMenuSelected(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMousePressed
        JOptionPane.showMessageDialog(this,
            "HANA ADILAH - 21120119120024\n",
            "LUVLY AUTHOR",
            JOptionPane.YES_OPTION);
    }//GEN-LAST:event_aboutMousePressed

    private void exitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_exitMenuSelected

    }//GEN-LAST:event_exitMenuSelected

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure want to exit?",
            "CONFIRMATION",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void rb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_1ActionPerformed
        if(rb_1.isSelected())
        {
            SILVER=350000;
            tf_harga.setText(String.valueOf(SILVER));
        }
    }//GEN-LAST:event_rb_1ActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        HOME xx;
        xx=new HOME();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    private void rb_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_2ActionPerformed
        if(rb_2.isSelected())
        {
            GOLD=360000;
            tf_harga.setText(String.valueOf(GOLD));
        }
    }//GEN-LAST:event_rb_2ActionPerformed

    private void rb_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_3ActionPerformed
        if(rb_3.isSelected())
        {
            BLACK=315000;
            tf_harga.setText(String.valueOf(BLACK));
        }
    }//GEN-LAST:event_rb_3ActionPerformed

    private void rb_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_4ActionPerformed
        if(rb_4.isSelected())
        {
            ROSE=375000;
            tf_harga.setText(String.valueOf(ROSE));
        }
    }//GEN-LAST:event_rb_4ActionPerformed

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hargaActionPerformed

    private void cbo_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_pembayaranActionPerformed

    }//GEN-LAST:event_cbo_pembayaranActionPerformed

    private void tf_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kembaliActionPerformed

    }//GEN-LAST:event_tf_kembaliActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        harga = Integer.parseInt(tf_harga.getText());
        bayar = Integer.parseInt(tf_bayar.getText());
        kembali = bayar-harga;
        tf_kembali.setText(String.valueOf(kembali));
    }//GEN-LAST:event_btn_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bracelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bracelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bracelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bracelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bracelet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JComboBox<String> cbo_pembayaran;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JTextField tf_bayar;
    private javax.swing.JTextField tf_data1;
    private javax.swing.JTextField tf_data3;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_kembali;
    // End of variables declaration//GEN-END:variables
}
