/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_p1 = new javax.swing.JPanel();
        lbl_p1 = new javax.swing.JLabel();
        btn_p1 = new javax.swing.JButton();
        panel_p2 = new javax.swing.JPanel();
        lbl_p2 = new javax.swing.JLabel();
        btn_p2 = new javax.swing.JButton();
        panel_p3 = new javax.swing.JPanel();
        lbl_p3 = new javax.swing.JLabel();
        btn_p3 = new javax.swing.JButton();
        panel_p4 = new javax.swing.JPanel();
        lbl_p4 = new javax.swing.JLabel();
        btn_p4 = new javax.swing.JButton();
        panel_p5 = new javax.swing.JPanel();
        lbl_p5 = new javax.swing.JLabel();
        btn_p5 = new javax.swing.JButton();
        lbl_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        about = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("• OFFICIAL MERCHANDISE •");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 610, 40));

        panel_p1.setBackground(java.awt.Color.pink);
        panel_p1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.pink, 2, true));

        lbl_p1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_p1.setText("LIGHTSTICK");
        lbl_p1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_p1.setBackground(new java.awt.Color(153, 153, 255));
        btn_p1.setText("BUY");
        btn_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_p1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p1Layout = new javax.swing.GroupLayout(panel_p1);
        panel_p1.setLayout(panel_p1Layout);
        panel_p1Layout.setHorizontalGroup(
            panel_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_p1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_p1)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panel_p1Layout.setVerticalGroup(
            panel_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_p1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(panel_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 100));

        panel_p2.setBackground(java.awt.Color.pink);
        panel_p2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.pink, 2, true));

        lbl_p2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_p2.setText("OBSESSION ALBUM");
        lbl_p2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_p2.setBackground(new java.awt.Color(153, 153, 255));
        btn_p2.setText("BUY");
        btn_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_p2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p2Layout = new javax.swing.GroupLayout(panel_p2);
        panel_p2.setLayout(panel_p2Layout);
        panel_p2Layout.setHorizontalGroup(
            panel_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_p2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btn_p2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_p2Layout.setVerticalGroup(
            panel_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_p2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(panel_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        panel_p3.setBackground(java.awt.Color.pink);
        panel_p3.setBorder(new javax.swing.border.LineBorder(java.awt.Color.pink, 2, true));

        lbl_p3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_p3.setText("KEYRING");
        lbl_p3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_p3.setBackground(new java.awt.Color(153, 153, 255));
        btn_p3.setText("BUY");
        btn_p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_p3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p3Layout = new javax.swing.GroupLayout(panel_p3);
        panel_p3.setLayout(panel_p3Layout);
        panel_p3Layout.setHorizontalGroup(
            panel_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_p3)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(panel_p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_p3Layout.setVerticalGroup(
            panel_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lbl_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_p3)
                .addGap(23, 23, 23))
        );

        jPanel1.add(panel_p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        panel_p4.setBackground(java.awt.Color.pink);
        panel_p4.setBorder(new javax.swing.border.LineBorder(java.awt.Color.pink, 2, true));

        lbl_p4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_p4.setText("PASSPORT HOLDER");
        lbl_p4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_p4.setBackground(new java.awt.Color(153, 153, 255));
        btn_p4.setText("BUY");
        btn_p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_p4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p4Layout = new javax.swing.GroupLayout(panel_p4);
        panel_p4.setLayout(panel_p4Layout);
        panel_p4Layout.setHorizontalGroup(
            panel_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_p4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_p4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_p4Layout.setVerticalGroup(
            panel_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lbl_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_p4)
                .addGap(19, 19, 19))
        );

        jPanel1.add(panel_p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        panel_p5.setBackground(java.awt.Color.pink);
        panel_p5.setBorder(new javax.swing.border.LineBorder(java.awt.Color.pink, 2, true));

        lbl_p5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_p5.setText("SFU BRACELET");
        lbl_p5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_p5.setBackground(new java.awt.Color(153, 153, 255));
        btn_p5.setText("BUY");
        btn_p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_p5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p5Layout = new javax.swing.GroupLayout(panel_p5);
        panel_p5.setLayout(panel_p5Layout);
        panel_p5Layout.setHorizontalGroup(
            panel_p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_p5)
                .addGap(30, 30, 30))
            .addGroup(panel_p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_p5, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_p5Layout.setVerticalGroup(
            panel_p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbl_p5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_p5)
                .addGap(22, 22, 22))
        );

        jPanel1.add(panel_p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 120, 100));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/waall (2).jpg"))); // NOI18N
        jPanel1.add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/icons8-information-20.png"))); // NOI18N
        about.setText("About");
        about.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMousePressed(evt);
            }
        });
        jMenuBar1.add(about);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/icon/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                exitMenuSelected(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                   
    private void aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMousePressed
        JOptionPane.showMessageDialog(this,
            "HANA ADILAH - 21120119120024\n",
            "LUVLY AUTHOR",
            JOptionPane.YES_OPTION);
    }//GEN-LAST:event_aboutMousePressed

    private void exitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_exitMenuSelected

    }//GEN-LAST:event_exitMenuSelected

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure want to exit?",
            "CONFIRMATION",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void btn_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_p1ActionPerformed
        lightstick xx;
        xx=new lightstick();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_p1ActionPerformed

    private void btn_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_p2ActionPerformed
        album xx;
        xx=new album();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_p2ActionPerformed

    private void btn_p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_p3ActionPerformed
        keyringg xx;
        xx=new keyringg();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_p3ActionPerformed

    private void btn_p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_p4ActionPerformed
        passport xx;
        xx=new passport();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_p4ActionPerformed

    private void btn_p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_p5ActionPerformed
        bracelet xx;
        xx=new bracelet();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_p5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JButton btn_p1;
    private javax.swing.JButton btn_p2;
    private javax.swing.JButton btn_p3;
    private javax.swing.JButton btn_p4;
    private javax.swing.JButton btn_p5;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_p1;
    private javax.swing.JLabel lbl_p2;
    private javax.swing.JLabel lbl_p3;
    private javax.swing.JLabel lbl_p4;
    private javax.swing.JLabel lbl_p5;
    private javax.swing.JPanel panel_p1;
    private javax.swing.JPanel panel_p2;
    private javax.swing.JPanel panel_p3;
    private javax.swing.JPanel panel_p4;
    private javax.swing.JPanel panel_p5;
    // End of variables declaration//GEN-END:variables
}
